<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{

    
    public function getFriendsSuggestion($id) {
        $em = $this->getEntityManager();
        
        $query= "
            SELECT person_id
            
            FROM person_friend

            WHERE friend_id IN (
                    SELECT person_id

                    FROM person_friend

                    WHERE friend_id = :id
                )
                AND person_id NOT IN (
                    SELECT person_id

                    FROM person_friend

                    WHERE friend_id = :id
                )
                AND person_id != :id
        ";
        $statement= $em->getConnection()->prepare($query);
        $statement->bindValue('id', $id);
        $statement->execute();
        $result = $statement->fetchAll();
        
        

        return $result;
    }

    public function getFriendsofFriends($id) {
        $em = $this->getEntityManager();

        $query = "
            SELECT DISTINCT person_id

            FROM person_friend

            WHERE friend_id IN (
                SELECT DISTINCT person_id
            
                FROM person_friend

                WHERE friend_id IN (
                        SELECT person_id

                        FROM person_friend

                        WHERE friend_id = :id
                    )
                    AND person_id NOT IN (
                        SELECT person_id

                        FROM person_friend

                        WHERE friend_id = :id
                    )
                    AND person_id != :id
            )
            AND person_id NOT IN (
                SELECT DISTINCT person_id
            
                FROM person_friend

                WHERE friend_id IN (
                        SELECT person_id

                        FROM person_friend

                        WHERE friend_id = :id
                    )
                    AND person_id NOT IN (
                        SELECT person_id

                        FROM person_friend

                        WHERE friend_id = :id
                    )
                    AND person_id != :id
            )
        ";
        $statement= $em->getConnection()->prepare($query);
        $statement->bindValue('id', $id);
        $statement->execute();
        $result = $statement->fetchAll();
        
        

        return $result;
    }

    public function getPeopleStats() {
        $em = $this->getEntityManager();
        $query = "
            SELECT friend_id,
                COUNT(person_id) AS num_friends
            
            FROM person_friend
            GROUP BY friend_id
            ORDER BY friend_id ASC, num_friends DESC
        ";
        $statement= $em->getConnection()->prepare($query);
        $statement->execute();
        $result = $statement->fetchAll();
        return $result;
    }
}
