<?php

namespace AppBundle\Repository;

/**
 * PersonFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonFriendRepository extends \Doctrine\ORM\EntityRepository
{
}
